export const ADD_COUNTRIES = 'ADD_COUNTRIES'
export const ADD_ACTIVITIES = 'ADD_ACTIVITIES'
export const ORDER = 'ORDER'
export const FILTER = 'FILTER'
// export const RESET = 'RESET'
// export const REMOVE_FAV = 'REMOVE_FAV'